# version of compose
version: "3.8"
# name: salamquran
# list of volumes and named them
volumes:
  # ********** nginx
  # salamquran_nginx_log:
  # ********** nginx
  salamquran_php_sessions:
  # ********** mysql
  salamquran_mysql_lib:
  # ********** redis
  salamquran_redis_data:
  # ********** postgresql
  # postgresql_data:
# list of networks
networks:
  salamquran_qanat:
    driver: bridge
# list of services
services:
# -------------------------------------------------- nginx
  nginx:
    container_name: salamquran_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    hostname: ${NGINX_HOSTNAME}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    tty: true
    extra_hosts:
        - "salamquran.local:host-gateway"
    volumes:
      # - salamquran_nginx_log:/var/log/nginx
      - ./src/:/var/www/html/
    environment:
      TZ: ${TIMEZONE}
    networks:
      - salamquran_qanat
    depends_on:
      - salamquran_php
# -------------------------------------------------- php
  php:
    container_name: salamquran_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    hostname: ${PHP_HOSTNAME}
    restart: always
    tty: true
    volumes:
      - ./src/:/var/www/html/
      - salamquran_php_sessions:/var/lib/php/sessions
      # - .docker/php/conf/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      TZ: ${TIMEZONE}
      SESSION_HANDLER: redis
      SESSION_PATH: tcp://salamquran_redis:${REDIS_PORT}?auth=${REDIS_PASSWORD}
      SESSION_MAX_TIME_LIFE: 86400
    networks:
      - salamquran_qanat
# -------------------------------------------------- mysql - db
  mysql:
    container_name: salamquran_mysql
    image: mysql
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}
    # env_file: mysql.env
    ports:
      - 3316:3316
    volumes:
      # - mysql_data:/var/usr/mysql
      - salamquran_mysql_lib:/var/lib/mysql
      # - ./services/mysql/production/my.cnf:/etc/mysql/my.cnf
    networks:
      - salamquran_qanat
# -------------------------------------------------- phpmyadmin
  phpmyadmin:
    container_name: salamquran_phpmyadmin
    image: phpmyadmin
    restart: on-failure
    # entrypoint: ["echo", "Service phpmyadmin disabled"]
    ports:
      - 8194:80
    networks:
      - salamquran_qanat
    depends_on:
      - salamquran_nginx
      - salamquran_php
      - salamquran_mysql
    profiles: ["phpmyadmin"]
    environment:
      PMA_HOST: salamquran_mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1000000000
# -------------------------------------------------- redis
  redis:
    container_name: salamquran_redis
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    # command: ["redis-server", "--appendonly", "yes"]
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - salamquran_redis_data:/data
    environment:
      #- REDIS_PASSWORD=${REDIS_PASSWORD}
      # - REDIS_PASSWORD=YOUR_REDIS_PASSWORD
      TZ: ${TIMEZONE}
    profiles: ["redis"]
    networks:
      - salamquran_qanat
#
# eol
